# Generated by Django 5.1.2 on 2024-10-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookingdata_rename_lname_userdata_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdata',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='lname',
        ),
    ]
