# Generated by Django 5.1.2 on 2024-10-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fname_bookingdata_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookingdata',
        ),
    ]
