# Generated by Django 5.1.2 on 2024-10-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_data_delete_bookingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_data',
            name='address',
        ),
        migrations.RemoveField(
            model_name='book_data',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='book_data',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='book_data',
            name='pick',
        ),
    ]
