# Generated by Django 5.1.2 on 2024-10-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_book_data_delete_userdata1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_data',
        ),
    ]
